#+TITLE: Spring Framework

* Progress
** Books
| name             | chapter                       | @                                    |
|------------------+-------------------------------+--------------------------------------|
| Spring in Action | 2 Developing web applications | 2.5 Choosing a view template library |
|                  |                               |                                      |

** SLOC
| Source Code      | folder | file | @ |
|------------------+--------+------+---|
| spring framework |        |      |   |
| spring-boot      |        |      |   |

* Controller
Class that handles requests and responds with information of some sort.

*@Controller*

* View
** JSP
* Validation
#+begin_src java
import javax.validation.Valid;
import org.springframework.validation.Errors;
#+end_src

@notNully

#+begin_src java
@Size(min=5, message="Name must be at least 5 characters long")
#+end_src

#+begin_src java
@NotBlank(message="Zip code is required")
#+end_src

#+begin_src java
// hibernate
@CreditCardNumber(message="Not a valid credit card number")
#+end_src

#+begin_src java
@Pattern(regexp="^(0[1-9]|1[0-2])([\\/])([2-9][0-9])$", message="Must be formatted MM/YY")
#+end_src

#+begin_src java
@Digits(integer=3, fraction=0, message="Invalid CVV")
#+end_src

* Model
* Toolings
** Containers
*** In-line run book examples
#+begin_src shell
podman run --name taco2 -it -v $PWD:/app -w /app -p 8080:8080 openjdk:17-jdk ./mvnw spring-boot:run
#+end_src
* Mapping
@RequestMapping
specifies that any request-handling methods in this controller
will handle requests whose path begins with /orders. When combined with the
method-level

@GetMapping

@RequestMappingGeneral-purpose
 request handling
@GetMappingHandles
HTTP GET requests
@PostMappingHandles
HTTP POST requests
@PutMappingHandles
 HTTP PUT requests
@DeleteMappingHandles
 HTTP DELETE requests
@PatchMappingHandles
 HTTP P
 ATCH requests
* Test
*@WebMvcTest*
* Annotations
*@SpringBootApplication*


*@SpringBootConfiguration*
Designates this class as a configuration class.

*@EnableAutoConfiguration*
Enables Spring Boot automatic configuration.

*@ComponentScan*
Enables component scanning.

*@Component*

*@Controller*

*@Service*

* Spring Landscape
** Spring Initializr
https://start.spring.io/
** Spring Framework
** Spring Boot
*** Test
*@SpringBootTest*
** Spring Data
** Spring Security
** Spring Integration
** Spring Batch
** Spring Cloud
** Spring Native
