#+TITLE: SSH, the Secure SHell

* Progress
| book        | chapter                         | @                                        |
|-------------+---------------------------------+------------------------------------------|
| SSH Mastery | Chapter 2: Common Configuration | Wildcards in OpenSSH Configuration Files |
|             |                                 |                                          |
* Definition
The Secure Shell (SSH) protocol sets up a secure Telnet session over a standard TCP/IP con-
nection and is employed for doing things like logging into other systems, running programs on
remote systems, and moving files from one system to another.

- default port: 22
- remote logins
- remote command execution
- shell access
- file transfer
- port forwarding
- network proxy services
- VPN tunneling.
* Base
- Every SSH server has a key pair.

** encryption
- cannot decrepit the message without the secret encryption key.

*** symmetric algorithm
uses the same key for both encryption and encryption.

*** asymmetric algorithm
 uses different keys for encryption and decryption.
* keys
** public key
~/.ssh/*.pub

- 0644
- shareable
** private key
~/.ssh/*

- 0600
- never share the private key!
* Configuration
- Port 22

| default location |                    |
|------------------+--------------------|
| linux            | /etc/ssh           |
| freebsd          | /usr/local/etc/ssh |
| osx              | /private/etc/ssh   |

** ssh_config
** sshd_config
server configuration
** ssh_*_key
server’s private keys

- should only be readable by root.
- ssh_host_ed25519_key
- ssh_host_rsa_key
- ssh_host_ecdsa_key

** ssh_*_key.pub
public key for that private keys

** ~/.ssh
- folder permission must be 0700
* traits
- ControlPersist
* commands
** options
*** -p
#+begin_src shell
ssh username@example.com -p 23
#+end_src
*** -i identity_file
  Selects a file from which the identity (private key) for public key authentication is read.  You can also specify a
  public key file to use the corresponding private key that is loaded in ssh-agent(1) when the private key file is not
  present locally.

#+begin_src shell
ssh -i ~/.ssh/id_ecdsa hsolo@server.admin.dom
#+end_src

*** -l
#+begin_src shell
ssh -l hsolo server.admin.com
#+end_src
*** -o
#+begin_src shell
ssh -o StrictHostKeyChecking=no server.admin.com
#+end_src
*** -v
* OpenSSH
** ssh
** sshd
** ssh-keygen
#+begin_src shell
ssh-keygen -t ecdsa -b 384
#+end_src

|    |                                                                              |
|----+------------------------------------------------------------------------------|
| -y | ead a private OpenSSH format file and print an OpenSSH public key to stdout. |
| -f | Specifies the filename of the key file.                                      |


** ssh-keyscan
** ssh-add
ssh-add adds private key identities to the authentication agent, ssh-agent(1).  When run without arguments, it adds the files
~/.ssh/id_rsa, ~/.ssh/id_dsa, ~/.ssh/id_ecdsa, ~/.ssh/id_ecdsa_sk, ~/.ssh/id_ed25519, and ~/.ssh/id_ed25519_sk.  After loading
a private key, ssh-add will try to load corresponding certificate information from the filename obtained by appending -cert.pub
to the name of the private key file.  Alternative file names can be given on the command line.

If any file requires a passphrase, ssh-add asks for the passphrase from the user.  The passphrase is read from the user's tty.
ssh-add retries the last passphrase if multiple identity files are given.

The authentication agent must be running and the SSH_AUTH_SOCK environment variable must contain the name of its socket for
ssh-add to work.


|    |                                                                          |
|----+--------------------------------------------------------------------------|
| -l | Lists fingerprints of all identities currently represented by the agent. |
| -d | removes identities from the agent                                        |
| -D | Deletes all identities from the agent.                                   |
|    |                                                                          |
** ssh-agent
 caches decrypted private keys


 |    |                                                        |
 |----+--------------------------------------------------------|
 | -a | Bind the agent to the UNIX-domain socket bind_address. |

** ssh-copy-id
** scp
** sftp
