#+TITLE: SSH

* definition
The Secure Shell (SSH) protocol sets up a secure Telnet session over a standard TCP/IP con-
nection and is employed for doing things like logging into other systems, running programs on
remote systems, and moving files from one system to another.

- default port: 22
* traits
- ControlPersist
* commands
** options
*** -p
#+begin_src shell
ssh username@example.com -p 23
#+end_src
* openssh
** ssh-add
ssh-add adds private key identities to the authentication agent, ssh-agent(1).  When run without arguments, it adds the files
~/.ssh/id_rsa, ~/.ssh/id_dsa, ~/.ssh/id_ecdsa, ~/.ssh/id_ecdsa_sk, ~/.ssh/id_ed25519, and ~/.ssh/id_ed25519_sk.  After loading
a private key, ssh-add will try to load corresponding certificate information from the filename obtained by appending -cert.pub
to the name of the private key file.  Alternative file names can be given on the command line.

If any file requires a passphrase, ssh-add asks for the passphrase from the user.  The passphrase is read from the user's tty.
ssh-add retries the last passphrase if multiple identity files are given.

The authentication agent must be running and the SSH_AUTH_SOCK environment variable must contain the name of its socket for
ssh-add to work.


|    |                                                                          |
|----+--------------------------------------------------------------------------|
| -l | Lists fingerprints of all identities currently represented by the agent. |
|    |                                                                          |
** ssh-agent
** ssh-copy-id
** scp
