#+TITLE: AWK

* Progress
** Books
| name                     | chapter            | @            |
|--------------------------+--------------------+--------------|
| Awk Programming Language | 2 The Awk Language | 2.1 Patterns |

** LDC
| Source Code | folder | file | @ |
|-------------+--------+------+---|
|             |        |      |   |
* Base
** Types
*** numbers
*** strings
** Collections
*** Array
#+begin_src shell
BEGIN {
    Say[0] = "hello";
    Say[1] = "world"
    print Say[0], Say[1]
 }
#+end_src

** Syntax
- pattern, action, files
- only pattern
- only action
- one or multiples files
** Patterns
*** BEGIN
The statements are executed once before any input has been read.

#+begin_src awk
BEGIN { statements }
#+end_src
*** END
The statements are executed once after all input has been read.

#+begin_src awk
END { statements }
#+end_src
*** Expression
|    |   |
|----+---|
| == |   |
| >  |   |
| <  |   |
| >= |   |
| <= |   |
*** Regular Expresion
#+begin_src awk
awk '/Susie/ { print NR, $1, $3 }'
#+end_src
*** Compound
|    |     |
|----+-----|
| && | and |
| ]] | or  |
|    |     |

#+begin_src shell
$2 >= 4 || $3 >= 20
( $2 < 4 && $3 < 20)
#+end_src
*** Range
A range pattern matches each input line from a line matched by pattern 1 to the
next line matched by pattern 2, inclusive; the statements are executed at each
matching line.

#+begin_src shell
pattern 1 , pattern 2 { statements }
#+end_src

*** data validation
#+begin_src shell
NF I= 3   { print $0, "number of fields is not equal to 3" }
$2 < 3.35 { print $0, "number of fields is not equal to 3" }
$2 < 3.35 { print SO, "rate is below minimum wage" }
$2 > 10   { print $0, "rate exceeds $10 per hour" }
#+end_src
** Fields
|     |                                  |
|-----+----------------------------------|
| $0  | whole line                       |
| $N  | field                            |
| NF  | number of fields in current line |
| $NF | last input files of current line |
| NR  | number of line                   |
** Conditionals
*** if/else
#+begin_src shell
$2 > 6 { n = n + 1; pay = pay + $2 * $3 }
END { if (n > 0)
        print n
    else
        print "meh"
    }
#+end_src
*** while
#+begin_src shell
{
    i = 1
    while (i <= $3) {
        printf("\t%.2f\n", $1 * (1 + $2) ^ i)
        i = i + 1
    }
}
#+end_src
*** for
#+begin_src shell
{
    for (i = 1; i <= $3; i = i + 1)
        printf("\t%.2f\n", $1 * (1 + $2) ^ i)
}
#+end_src
** Printing
*** printf
#+begin_src awk
printf (format, value 1 , value 2 , ... , valueN)

{ printf("total pay for %s is $%.2f\n", $1, $2 * $3) }
#+end_src
*** print
** Comments
*** #
A comment starts with the character # and finishes at the end of the line

#+begin_src awk
{ print S1, $3 } # meh

{ print \
        $1, # country name
        $2, # area in thousands of square miles
        $3 } # population in millions
#+end_src

** Functions
*** substr
Return a length-character-long substring of string, starting at character number
start. The first character of a string is character number one.

#+begin_src awk
substr("washington", 5, 3) #  returns "ing".
#+end_src

*** gsub
Search target for all of the longest, leftmost, nonoverlapping matching
substrings it can find and replace them with replacement. The ‘g’ in gsub()
stands for “global,” which means replace everywhere.

*** misc
#+begin_src shell
    pattern action                files
awk '$3 > 0 { print $1, $2 * $3}' ~/emp.data

awk '{ print}' ~/emp.data

awk '$3 > 0' ~/emp.data

awk { print "total pay for", $1, "is", $2 * $3 }

$2 * $3 > 50 { printf("$%.2f for %s\n", $2 * $3, $1) }

#+end_src
* Commands

*-F*

*-f*
#+begin_src awk
#! /usr/bin/awk -f

#use BEGIN sepecial character to set FS built-in variable
BEGIN { FS=":" }

#search for username: aaronkilik and print account details
/aaronkilik/ { print "Username :",$1,"User ID :",$3,"User GID :",$4 }
#+end_src
