#+TITLE: Network

* Progress
|                              |             |        |
|------------------------------+-------------+--------|
| Network+ N10-008 Todd lameun | 6 Protocols | TCP/IP |

* Load balancing

* Ports
** Well-known Ports
also known as system ports

- 0 and 1023
** Registered Ports
** Dynamic Ports

* Subneting
* OSI Model
** Concepts
- 7 layers
- works for almost every type of network, even extremely old and long-obsolete ones
** Layers
*** Layer 7 Application
*** Layer 6 Presentation
*** Layer 5 Session
*** Layer 4 Transport
*** Layer 3 Network
*** Layer 2 Data Link
- Data Link layer
- Switches handle traffic using MAC addresses
- NIC is in the Data Link layer and the Physical layer
*** Layer 1 Physical
- defines the method of moving data between computers
- cabling and central box are part of the Physical layer
- doesn’t care what data goes through
- it just moves the data from one system to another system
- NIC interface between the PC and the network
* LAN
- IP address
- Ethernet MAC Adress
* Physical
** Cable
*** UTP
- unshielded twisted pair
- contains four pairs of wires
*** central box
* Terms
  - hotspot
  - VOIP
  - IPTV
  - RFID
  - 2 family (p2p)
  - desktop sharing
** Mac Adress
** OSI layers
** TCP/IP
** NIC
** FCS
** PANs
Personal Area Networks let devices communicate over the range of a person.

- Bluetooth
** LAN
A Local Area Network is a private network that operates within and nearby
a single building such as a home, office, or factory.

- Access Point: AP
- IEEE 802.11: WIFI
- IEEE 802.3: Ethernet
- switch
- VLAN
** MAN
Metropolitan Area Networks
** Subnet Mask
A subnet mask is a number that distinguishes the network address and the host
address within an IP address.

11111111111111111111111100000000
** Mac adress
- uses Address Resolution Protocol to figure out the MAC address based on the destination IP address
* hostname
** def
A hostname is a label assigned to a device (a host) on a network. It
distinguishes one device from another on a specific network or over the
internet. The hostname for a computer on a home network may be something like
new laptop, Guest-Desktop, or FamilyPC.
* url
Uniform Resource Locator
** def
Abbreviated as URL, a Uniform Resource Locator is a way of identifying the
location of a file on the internet. They're what we use to open not only
websites, but also to download images, videos, software programs, and other
types of files that are hosted on a server.
