#+TITLE: TCP/IP

* Progress

| name                                   | chapter              | @                |
|----------------------------------------+----------------------+------------------|
| Unix Linux System Administration Books | 13 Networking Basics | Ethernet framing |
| Redes TCP/IP - Udemy Gabriel Torres    |                      |                  |

* Definition
A protocol that provides quick, automatic, and central management for the
distribution of IP addresses within a network. It's also used to configure the
subnet mask, default gateway, and DNS server information on the device.
* IP
The Internet Protocol, which routes data packets from one machine to another

An IP address, short for Internet Protocol address, is an identifying number for
network hardware connected to a network. Having an IP address allows a device to
communicate with other devices over an IP-based network like the internet.


- 32 bits integers converted to decimal: 11000000.10101000.00000100.00000010 -> 192.168.1.1
- MAC and IP address must be unique on a network

*** IPv4
This type of address—four values ranging from 0 to 255, separated by three
periods: 192.168.1.115

- 4 billion unique IP addresses (232)
- 32-bit numerical number
- hexadecimal
- uses 4-byte IP addresses

#+begin_src conf
151.101.65.121
#+end_src

**** MAC - Media Access Control
**** ARP - Address Resolution Protocol
**** 14 Fields
- Version
- Length
- Protocol
- Time to live
- Differentiated services code point (DSCP)
*** IPv6
- 340 trillion, trillion, trillion addresses (2128)
- no IP address collisions caused by private addresses
- Auto-configuration
- No reason for Network Address Translation (NAT)
- Efficient routing
- Easier administration
- Built-in privacy
- 16 bytes

#+begin_src conf
3ffe:1900:4545:3:200:f8ff:fe21:67cf
#+end_src

*** Types of IP Addresses
**** private IP addresses
- provide a way for devices that don't need a connection to the internet

***** def
A private IP address is an IP address that's reserved for internal use behind a
router or other Network Address Translation (NAT) device, apart from the public.
Private IP addresses are in contrast to public IP addresses, which are public
and can't be used within a home or business network. Sometimes a private IP
address is also referred to as a local IP address.

***** range
- 10.0.0.0 to 10.255.255.255
- 172.16.0.0 to 172.31.255.255
- 192.168.0.0 to 192.168.255.255

***** Automatic Private IP Addressing
- 169.254.0.0 to 169.254.255.255

Automatic Private IP Addressing (APIPA) is a DHCP fail-safe that protects a
computer system from failure. It invokes a standby mechanism for local Internet
Protocol version 4 (IPv4) networks supported by Microsoft Windows. With APIPA,
DHCP clients can obtain IP addresses even when DHCP servers are not functional.

***** Reserved IP Addresses
- 0.0.0.0 to 0.255.255.255
- 127.0.0.0 to 127.255.255.255

****** 127.0.0.1.
This address is called the loopback address and is used to test the network
adapter or integrated chip. No traffic addressed to 127.0.0.1 is sent over the
local network or public internet.

**** public IP addresses
**** static IP addresses
- doesn't have DHCP enabled
-  doesn't support DHCP

**** dynamic IP addresses
- assigned by a DHCP server is a dynamic IP address.
*** ICMP
*** IGMP
** EXAM TIP
you should memorize that 0 = 00000000 and 255 = 11111111.
* IPAM
IP address management (IPAM) is a means of planning, tracking, and managing IP addresses within
the network. IPAM has both DNS and DHCP services, so each service is notified of changes in the other.
* ICMP
The Internet Control Message Protocol, which defines several kinds
of low-level support for IP, including error messages, routing assistance,
and debugging help

ICMP handles low-level connectivity messages between hosts.
* PDU
* UDP
The User Datagram Protocol, which implements unverified, one-
way data delivery

- carry application data between hosts
- flexibility
- simplicity
- connectionless protocol
- voip
- online gaming, dns, dcp
-
* TCP
The Transmission Control Protocol, which implements reliable, full
duplex, flow-controlled, error-corrected conversations.

Offers the minimal services needed to transmit data over the network.

- connection-oriented protocol
- carry application data between hosts
- error-checking
- congestion control
- retransmission of lost data
- http, ftp, email
* ARP
The Address Resolution Protocol, which translates IP addresses to
hardware addresses
* Port


* DNS
- udp/ip
* TSL
- substitute ssl
* SSL
* DHCP
Dynamic Host Configuration Protocol
* DoD Model
- Process Application
- Host-to-Host
- Internet
- Network Access
