#+title: SOAP

* SOAP
 - Web Service Description Language
 - uses a standard XML schema (XSL) to encode XML
 - is a protocol for exchanging information encoded in Extensible Markup Language (XML) between a client and a procedure or service that resides on the Internet.
 - used by a variety of transport protocols in addition to HTTP, for example, FTP and SMTP
 - HTTP for synchronous data exchange and SMTP or FTP for asynchronous interactions

** benefits
- implemented using a variety of protocols
** mm
- considered a complex message format with a lot of ins and outs to the specification.
- verbose nature of XML which is the format upon which SOAP is based, coupled with the reliance on external namespaces to extend the basic message format makes the protocol bulky and at times difficult to manage.
- can get quite large
- legacy protocol.
-

** Soap Message
   - hierarchical structure in which the root element is the <soap:Envelope>
   - root element can have three child elements
   - <soap:Header>, <soap:Body> and <soap:Fault>
   - <soap:Body> is required
   - optional element, <soap:Header> is used, it must be the first child element within the parent element,
   - <soap:Envelope> and when the optional element <soap:Fault> is used, it must be a child of the element, <soap:Body>.
    -<soap:Header> provides header information relevant to the message.
   - <soap:Body> describes the payload of the message
   - element <soap:Fault> contains error information that’s occurred during the transmission and consumption of the message.
   - SOAPAction is an HTTP header attribute that tells the host that the incoming request is a SOAP message.

#+begin_src xml
 POST /BobsTickers HTTP/1.1
 Host: www.example.org
 Content-Type: application/soap+xml; charset=utf-8
 Content-Length: 275
 SOAPAction: "http://cooltickers.org/soap"

 <?xml version="1.0"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:m="http://www.exampletickers.org">
  <soap:Header>
  </soap:Header>
  <soap:Body>
    <m:GetStockPriceRequest>
      <m:StockName>IBM</m:StockName>
    </m:GetStockPriceRequest>
  </soap:Body>
</soap:Envelope>
#+end_src
