#+TITLE: Node.js

* Summary
    :PROPERTIES:
    :TOC:      :include all :depth 2 :ignore this
    :END:
  :CONTENTS:
  - [[#progress][Progress]]
    - [[#books][Books]]
    - [[#sloc][SLOC]]
    - [[#skills][SKills]]
  - [[#features][Features]]
    - [[#nubers][Nubers]]
  - [[#concepts][Concepts]]
  - [[#books][Books]]
    - [[#eloquent-javascript][Eloquent JavaScript]]
  - [[#sites][Sites]]
    - [[#web-js---misc][Web JS - Misc]]
    - [[#web-js---online-tools][Web JS - Online Tools]]
  - [[#frameworks][Frameworks]]
  - [[#refactoring][Refactoring]]
  - [[#articles][Articles]]
  - [[#interview][Interview]]
  :END:
* Progress
** Books
| Books         | Cap                          | @                          |
|---------------+------------------------------+----------------------------|
| Node cookbook | 3: Streams, Streams, Streams | 11.6.1 JSON Customizations |

** SLOC
| Project   | folder                  | file         | @ |
|-----------+-------------------------+--------------+---|
| draggable | src/Draggable/DragEvent | DragEvent.js |   |
| inquirer  |                         |              |   |

* Cli
** options
|                        |   |
|------------------------+---|
| --print or -p          |   |
| --eval or -e <COMMAND> |   |
| -i                     |   |
| --check or -c          |   |
| --require or -r        |   |
** env
|             |   |
|-------------+---|
| FORCE_COLOR |   |
| NO_COLOR    |   |
* Library
** [[https://nodejs.org/api/fs.html][fs]]
*** readFileSync
*** readdirSync
*** writeFileSync
*** readFile
** [[https://nodejs.org/docs/latest-v16.x/api/process.html][process]]
*** stdin
*** stdout
*** env
#+begin_src js
process.env.USER_ID // "239482"
process.env.USER_KEY // "foobar"
process.env.PATH?.split(':') ?? ['/bin', '/usr/bin', '/sbin/']
#+end_src
*** cwd
*** exit
*** on
Ignore Ctrl-C by registering a signal handler function with

#+begin_src js
process.on("SIGINT", ()=>{})
#+end_src

Unhandled Promise rejections are expected to become fatal errors

#+begin_src js
process.on("unhandledRejection", (reason, promise) => {
// reason is whatever value would have been passed to a .catch() function
// promise is the Promise object that rejected
});
#+end_src


*** setUncaughtExceptionCaptureCallback

register a global handler function that will be invoked instead of crashing

#+begin_src js
process.setUncaughtExceptionCaptureCallback(e => {
console.error("Uncaught exception:", e);
});
#+end_src
** [[https://nodejs.org/api/path.html][path]]
*** join
*** basename
**** extname
** net
**
** HTTPServer
** os
*** hostname
*** release
*** cpus
*** fremem
*** arch
*** tempdir
*** inspect
*** networkInterfaces(
*** type

* EventEmitter
** methods
#+begin_src js
import EventEmitter from 'events';

export class Pulser extends EventEmitter {
    start() {
        setInterval(() => {
            console.log(`${new Date().toISOString()} >>>> pulse`);
            this.emit('pulse');
            console.log(`${new Date().toISOString()} <<<< pulse`);
        }, 1000);
    }
}
#+end_src

#+begin_src js
import { Pulser } from './pulser.mjs';

// Instantiate a Pulser object
const pulser = new Pulser();
// Handler function
pulser.on('pulse', () => {
    console.log(`${new Date().toISOString()} pulse received`);
});
// Start it pulsing
pulser.start();
#+end_src

*** .emit
send data along with an event

#+begin_src js
this.emit('eventName', data1, data2, ..);
#+end_src

When the program receives the event, the data appears as arguments to the
callback function. Your program listens to this event, as follows:

#+begin_src js
emitter.on('eventName', (data1, data2, ...theArgs) => {
  // act on event
});

#+end_src

*** .on

* Asynchronous
** callbacks
** Promises
** async/await

* Files
** .mjs
If you save your JavaScript code in a file that ends with .mjs, then Node will
always load it as an ES6 module, will expect it to use import and export , and
will not provide a require() function.

** .cjs
save your code in a file that ends with .cjs, then Node will always treat it as
a CommonJS module, will provide a require() function, and will throw a
SyntaxError if you use import or export declarations.

* Frameworks
https://adonisjs.com/

* ES6
Node allows ES6 modules to load CommonJS modules using
the import keyword. The reverse is not true, however: a CommonJS module cannot
use require() to load an ES6 module.
