#+TITLE: Kubernetes

* Progress
** Books
| Books                            | Chapters                                                    | @ |
|----------------------------------+-------------------------------------------------------------+---|
| Kubernetes – An Enterprise Guide | Services, Load Balancing, ExternalDNS, and Global Balancing |   |
| The Book of Kubernetes_          |                                                             |   |

* Base
** Container
*** lifecycle
**** PreStop
**** PostStart
** Controllers
*** Long-lived
**** Deployments
**** StatefulSets
**** DaemonSets
*** Short-lived
**** Jobs
**** CronJobs
** Control Plane
- suggested that you have at least three master nodes
** Cluster
*** Cluster master
*** Worker nodes
- machine or vm
**** components
***** kubelet
-
***** kube-proxy
***** container runtime
** ConfigMap
A ConfigMap is an API object used to store non-confidential data in key-value
pairs. Pods can consume ConfigMaps as environment variables, command-line
arguments, or as configuration files in a volume.

A ConfigMap allows you to decouple environment-specific configuration from your
container images, so that your applications are easily portable.
** Cronjob
#+begin_src yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
#+end_src

** CustomResourceDefinitions
allow to extend Kubernetes by integrating their application into a cluster as a standard resource.
** DaemonSets
A DaemonSet ensures that all (or some) Nodes run a copy of a Pod. As nodes are
added to the cluster, Pods are added to them. As nodes are removed from the
cluster, those Pods are garbage collected. Deleting a DaemonSet will clean up
the Pods it created.
** Deployments
A Deployment provides declarative updates for Pods and ReplicaSets.

- manage your upgrades declaratively
- roll back to previous revisions

You describe a desired state in a Deployment, and the Deployment Controller
changes the actual state to the desired state at a controlled rate. You can
define Deployments to create new ReplicaSets, or to remove existing Deployments
and adopt all their resources with new Deployments.
** Endpoints
Maps a service to a Pod or Pods.
** Events
Displays any events for a namespace.
** HealthChecks
*** livenessProbe
*** readinessProbe
*** startup
** HorizontalPodAutoscalers
provide the ability to scale an application based on a set of criteria.
** Jobs
** Ingress
An API object that manages external access to the services in a cluster, typically HTTP.

Ingress exposes HTTP and HTTPS routes from outside the cluster to services
within the cluster. Traffic routing is controlled by rules defined on the
Ingress resource.
** Master
*** API server
*** etcd
*** scheduler
*** kube-controller-manager
*** cloud-controller-manager

*** Contexts
** Namespaces
is a resource to divide a cluster into logical units.

*** kube-system
 The namespace for objects created by the Kubernetes system
*** kube-public
This namespace is created automatically and is readable by all users (including
those not authenticated). This namespace is mostly reserved for cluster usage,
in case that some resources should be visible and readable publicly throughout
the whole cluster. The public aspect of this namespace is only a convention, not
a requirement.
*** default
The default namespace for objects with no other namespace
** Nodes
a cluster-level resource that is used to interact with the cluster's nodes.
** Volumes
** Persistent Volume Claims
used by a Pod to consume persistent storage.
** Persistent Volume
used by PVCs to create a link between the PVC and the underlying storage system.
** Pods
Pods are the smallest deployable units of computing that you can create and manage in Kubernetes.

A Pod (as in a pod of whales or pea pod) is a group of one or more containers,
with shared storage and network resources, and a specification for how to run
the containers.

- immutable objects
- single-container
- multi-container
- defined declaratively in manifest files
- deployed via higher-level controllers

*** multi-container pod
**** patterns
***** Sidecar pattern
- sidecar augments or performs a secondary task for the main application container.
***** Adapter pattern
the helper container translate output from the main container to a format required B an external system

- variation of the sidecar pattern

eg: translate NGINX logs to Prometheus.

***** Ambassador pattern
brokers connectivity to an external system.

- variation of the sidecar pattern
***** Init pattern
init container starts and completes before the main app container, only once.
*** single-container pod
*** state
**** status
**** condition
**** container
- running
- terminated
**** pending
**** succeded
**** failed
**** unknown
** ReplicaSet
A ReplicaSet's purpose is to maintain a stable set of replica Pods running at
any given time. As such, it is often used to guarantee the availability of a
specified number of identical Pods.

*** ReplicaController (old way)
A ReplicationController ensures that a specified number of pod replicas are
running at any one time. In other words, a ReplicationController makes sure that
a pod or a homogeneous set of pods is always up and available.
** Resource Quotas
When several users or teams share a cluster with a fixed number of nodes, there
is a concern that one team could use more than its fair share of resources.

Resource quotas are a tool for administrators to address this concern.

A resource quota, defined by a ResourceQuota object, provides constraints that
limit aggregate resource consumption per namespace. It can limit the quantity of
objects that can be created in a namespace by type, as well as the total amount
of compute resources that may be consumed by resources in that namespace.

#+begin_src yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: base-memory-cpu
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 8Gi
    limits.cpu: "4"
    limits.memory: 16Gi
#+end_src

** Secrets
- Base64-encoded strings

*** Env Vars
*** File
- dotenv
- yaml files

*** Vaults
** Service
An abstract way to expose an application running on a set of Pods as a network service.

- defaults to ClusterIP.
- receive an IP address that will remain the same

#+begin_src yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-web-frontend
  name: nginx-web
spec:
ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: nginx-web
#+end_src

*** NodePort
- A network type that exposes the service to a random port between ports 30000 and 32767

**** TargetPort
**** Port
*** ClusterIP
*** LoadBalancer
- requires an add-on to use inside a cluster
*** ExternalName
** Service Account
A service account provides an identity for processes that run in a Pod.

- a secret will also be created

#+begin_src yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: monitoring
#+end_src
** StatefulSets
** PodSecurityPolicies
how cluster protects your nodes from your containers. They allow you to limit the
actions that a Pod can execute in a cluster.
** ClusterRoleBindings
** ClusterRoles
** RoleBindings
how to associate a Role or ClusterRole with a subject and namespace.
** Roles
combines API groups and actions to define a set of permissions that can be assigned to a subject.
** CSI drivers
** CSI nodes
** Storage classes
used to define a storage endpoint.
* Components
** kube-apiserver
** kube-scheduler
** kube-controller-manager
*** node
*** replication
*** endpoints
*** serviceaccounts
*** namespace
** Etcd
** cloud-controller-manager
*** node
*** route
*** service
*** volume controllers
** worker nodes
*** kubelet
- responsible for running the actual containers
*** kube-proxy
- responsible for routing network communication between a Pod and the network
** Container runtime
* Manifest
** apiVersion
*** v1
*** apps
** kind
*** Deployment
*** Namespace
*** Pod
*** PersistentVolumeClaim
*** ReplicaSet
*** ReplicaController
*** Service
*** Replicator
*** NetworkPolicy
defines how network traffic, both ingress (incoming) and egress (outgoing), can flow through your cluster.
*** RoleBinding
** metadata
*** name
*** namespace
*** labels
**** type
**** app
** spec
*** labels
*** hard
**** pods
*** containers
**** name
***** image
*** initContainers
specialized containers that run before app containers in a Pod. Init containers
can contain utilities or setup scripts not present in an app image.
*** NodeSelector
** Object
** Status

** example

#+BEGIN_SRC yaml
apiVersion: apps/v1
Kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
#+END_SRC
* Config File
** Clusters
** Users
* Challenges
** On premisses 1m/2n
- k8s on-premisse com 2 nodes E 1 Master
