#+TITLE: Java

* Summary
:PROPERTIES:
:TOC:      :include all
:END:
:CONTENTS:
- [[#summary][Summary]]
- [[#progress][Progress]]
  - [[#books][Books]]
  - [[#sloc][SLOC]]
- [[#base][Base]]
  - [[#types][Types]]
    - [[#integers][Integers]]
      - [[#byte][byte]]
      - [[#short][short]]
      - [[#int][int]]
      - [[#long][long]]
    - [[#floating][Floating]]
      - [[#float][float]]
      - [[#double][double]]
    - [[#strings][Strings]]
    - [[#characters][Characters]]
    - [[#boolean][Boolean]]
  - [[#variables][Variables]]
  - [[#objects][Objects]]
    - [[#passed-as-param][Passed as Param]]
  - [[#classes][Classes]]
    - [[#access-control][Access Control]]
      - [[#public][Public]]
      - [[#private][Private]]
      - [[#protected][Protected]]
    - [[#static][Static]]
    - [[#final][Final]]
    - [[#seal][Seal]]
    - [[#inheritance][inheritance]]
    - [[#super][super]]
    - [[#abstract-classes][Abstract Classes]]
- [[#library][Library]]
  - [[#string][String]]
  - [[#object][Object]]
    - [[#methods][methods]]
- [[#scripting][Scripting]]
:END:
* Progress
** Books
| name                    | chapter                   | @ |
|-------------------------+---------------------------+---|
| Java Complete Reference | 9 Packages and Interfaces |   |
| Effective Java 9        |                           |   |

** SLOC
| Source Code | folder | file | @ |
|-------------+--------+------+---|
| jdk         |        |      |   |

* Base
** Types
*** Integers
- are signed, positive and negative values

**** byte
- smallest integer type
- –128 to 127

#+begin_src java
byte b, c;
#+end_src

**** short
- range from –32,768 to 32,767

#+begin_src java
short s;
short t;
#+end_src
**** int
- range from –2,147,483,648 to 2,147,483,647
- byte and short values in expressions are promoted to int when evaluated
#+begin_src java
int x = 0b1010; // integer binary
int y = 123_456_789;
int y = 123___456___789;
#+end_src
**** long
*** Floating
- real numbers
- IEEE–754
- defaults to double precision
- supports hexadecimal floating-point

#+begin_src java
0x12.2P2 // hexadecimal fp
double num = 9_423_497_862.0;
#+end_src

**** float
- 1.4e–045 to 3.4e+038
- single-precision
- takes half as much space as double precision
- imprecise when the values are either very large or very small

#+begin_src java
float hightemp, lowtemp;
#+end_src
**** double
- 4.9e–324 to 1.8e+308

#+begin_src java
// Compute the area of a circle.
class Area {
    public static void main(String[] args) {
        double pi, r, a;
        r = 10.8; // radius of circle
        pi = 3.1416; // pi, approximately
        a = pi * r * r; // compute area
        System.out.println("Area of circle is " + a);
    }
}
#+end_src
*** Strings
#+begin_src java
"Hello World"
"two\nlines"
" \"This is in quotes\""
#+end_src
*** Characters
- store characters
- range of 0 to 65,535
- able to manipulate with the integer operators

#+begin_src java
'\u0061' // ISO-Latin-1 'a'
'\ua432 ' // ꐲ - Japanese Katakana character.

// Demonstrate char data type.
class CharDemo {
    public static void main(String[] args) {
        char ch1, ch2;
        ch1 = 88; // code for X
        ch2 = 'Y';
        System.out.print("ch1 and ch2: ");
        System.out.println(ch1 + " " + ch2);
    }
}
#+end_src

*** Boolean
- true
- false
- wont convert into any numerical representation

#+begin_src java
// Demonstrate boolean values.
class BoolTest {
    public static void main(String[] args) {
        boolean b;
        b = false;
        System.out.println("b is " + b);
        b = true;
        System.out.println("b is " + b);
        // a boolean value can control the if statement
        if(b) System.out.println("This is executed.");
        b = false;
        if(b) System.out.println("This is not executed.");
        // outcome of a relational operator is a boolean value
        System.out.println("10 > 9 is " + (10 > 9));

    }
}
#+end_src
** Variables
- an identifier, a type, and an optional initialize
- has a scope, which defines their visibility, and lifetime
- must be declared before being used

#+begin_src java
int a, b, c;
int d = 3, e, f = 5;
byte z = 22;
double pi = 3.14159;
char x = 'x';
#+end_src
** Objects
*** Passed as Param
- Pass as reference, will change the object passsed as param outside of method.
** Classes
*** Access Control
**** Public
- can be accessed by any other code
- default access
**** Private
- can only be accessed by other members of its class.
**** Protected
- applies only when inheritance is involved
*** Static
- can only directly call other static methods of their class
- can only directly access static variables of their class.
- cannot refer to this or super
- are, essentially, global variables
*** Final
- prevents its contents from being modified, making it, essentially, a constant.
- you must initialize a final field when it is declared.
- can give it a value when it is declared or assign it a value within a constructor


- prevents methods overriding
- sometimes provide a performance enhancement (inline calls)

#+begin_src java
class A {
	final void meth() {
		System.out.println("This is a final method.");
	}
}
class B extends A {
	void meth() { // ERROR! Can't override.
		System.out.println("Illegal!");
	}
}
#+end_src

- prevents inheritance

#+begin_src java
final class A {
	//...
}
// The following class is illegal.
class B extends A { // ERROR! Can't subclass A
	//...
}
#+end_src
*** Seal
*** inheritance
- inherits all from super object
- single-inheritance
- private on superclass elements are not inherited by subclasses

#+begin_src java
class A {
	int i, j;
	void showij() {
		System.out.println("i and j: " + i + " " + j);
	}
}
// Create a subclass by extending class A.
class B extends A {
	int k;
	void showk() {
		System.out.println("k: " + k);
	}
	void sum() {
		System.out.println("i+j+k: " + (i+j+k));
	}
}

#+end_src
*** super
- must always be the first statement executed inside a subclass’ constructor.
*** Abstract Classes

* Library
** String
** Object
- superclass of all other classes
- reference variable of type Object can refer to an object of any other class.
*** methods
|           |   |
|-----------+---|
| clone     |   |
| equals    |   |
| finalize  |   |
| getClass  |   |
| hashCode  |   |
| notify    |   |
| notifyAll |   |
| toString  |   |
| wait      |   |


* Scripting
- remove .java extension
- chmod +x
- add shebang w/ *--source N*
- java dependencies can be added w/ *-cp /path/to/xxx.jar*

#+begin_src java
#!/usr/bin/java --source 17

public class HelloScripting {
	public static void main(String[] args) {
		System.out.println("Hello " + args[0]);
	}
}

#+end_src
