#+TITLE: PHP

* Progress
** Resource
| name                    | chapter | @          |
|-------------------------+---------+------------|
| PHP Language Reference  | Types   | Boolean    |
| YT Edson Maia           | OOP     | Prediction |
| The Art of modern PHP 8 |         |            |

** SLOC
| Source Code | folder | file      | @ |
|-------------+--------+-----------+---|
|             |        |           |   |

* Base
** Types
*** Booleans
A bool expresses a truth value. It can be either *True* or *False*.

*Falsy values*

- the boolean false itself
- the integer 0 (zero)
- the floats 0.0 and -0.0 (zero)
- the empty string, and the string "0"
- an array with zero elements
- the special type NULL (including unset variables)
- SimpleXML objects created from attributeless empty elements, i.e. elements which have neither children nor attributes.

*Truthy values*

- every other value is considered true (including any resource and NAN).
- non-zero integers include negatives ones: -1 or 1

#+begin_src php
<?php
$foo = True;
$bar = False;
?>
#+end_src

*** Integers
A number of the set ℤ = {..., -2, -1, 0, 1, 2, ...}.

 - decimal (base 10), hexadecimal (base 16), octal (base 8) or binary (base 2) notation
- PHP 8.1.0: octal notation can also be preceded with 0o or 0O.

#+begin_src php
<?php
$a = 1234; // decimal number
$a = 0123; // octal number (equivalent to 83 decimal)
$a = 0o123; // octal number (as of PHP 8.1.0)
$a = 0x1A; // hexadecimal number (equivalent to 26 decimal)
$a = 0b11111111; // binary number (equivalent to 255 decimal)
$a = 1_234_567; // decimal number (as of PHP 7.4.0)
?>
#+end_src

#+begin_src php

<?php
var_dump(25/7);         // float(3.5714285714286)
var_dump((int) (25/7)); // int(3)
var_dump(round(25/7));  // float(4)
?>

#+end_src

**** functions
- intdiv()
- intval()
- round()

*** Floating numbers
Floating point numbers (also known as "floats", "doubles", or "real numbers")
#+begin_src php

<?php
$a = 1.234;
$b = 1.2e3;
$c = 7E-10;
$d = 1_234.567; // as of PHP 7.4.0
?>

#+end_src
*** String
#+begin_src php
<?php
echo "He4rtDevs <3";
echo "Melhor grupo do mundo para devs iniciantes";
#+end_src
** Collection Types
*** Array
*** Array Associative
#+begin_src php
<?php

$array = array(
    "foo" => "bar",
    "bar" => "foo",
);


$array = [
    "foo" => "bar",
    "bar" => "foo",
];

?>
#+end_src

** Variables
** Functions
** Commentary
#+begin_src shell

#+end_src
** Tags
***  <?php ?>
** Classes
*** Abstract
** Interface
** Autoload
* Library
** Global
*getenv*
*abs()*

*echo*
Output one or more strings

#+begin_src php
<?php

echo "He4rtDevs";
echo 123456;
#+end_src

*var_dump*
Dumps information about a variable

#+begin_src php
<? php
var_dump((bool) "");
var_dump(new stdClass());
#+end_src

*error_reporting(E_ALL)*
** Global Variables
*** $argn
* Misc
** Scripting
#+begin_src php
#!/usr/bin/env php
<?php

echo 'Meh';
$options = getopt("hcoprf:t:");
var_dump($options);

?>
#+end_src

* Commands
** options
*** -r <code>
#+begin_src shell
php -r 'echo "one two three";'
#+end_src
*** -R
#+begin_src shell
cat file.txt | php -R 'echo ">: " . $argn . "\n";'
#+end_src
*** -S <PORT>
#+begin_src shell
php -S localhost:8081 # go to https://localhost:8081/index.php in a browser
#+end_src

* Jobs
** PicPay Pleno
MAIN RESPONSIBILITIES
Construir soluções com padrões de qualidade de código
Criar funcionalidades pensando na performance e segurança
Implementar testes para melhor manutenção
Manter documentações dos serviços
REQUIREMENTS AND SKILLS
Experiência com as seguintes ferramentas:



PHP 8.*;
Frameworks Laravel ou Lumen, com ênfase em aplicações RESTful;
Armazenamento de dados em MySQL (ou outros bancos relacionais) ou MongoDB (ou outros bancos não relacionais);
Ambiente de desenvolvimento com Docker;
Atenção para qualidade de código e design patterns;
Desenvolvimento orientado a testes;
Versionamento de códigos utilizando Git.


Será um diferencial se tiver experiência com:



Metodologias ágeis;
Design e desenvolvimento de micro serviços horizontalmente escaláveis;
Jobs de alto desempenho e comunicação entre serviços utilizando soluções de fila como Beanstalk, RabbitMQ, Kafka, etc;
Conhecimento dos riscos comuns de segurança (OWASP).
** Xteam
Job Description
PHP Developer
Most Important

    Expert experience with PHP, and expertise with the newest versions of PHP
    Extensive experience with various PHP frameworks (Laravel/Symfony/CodeIgniter/CakePHP/Yii, etc.)
    Solid skills in SQL databases (MySQL, PostgreSQL, MariaDB etc)
    Experience writing high-quality unit tests
    Ability to build and consume RESTful web services
    Code optimization and performance improvements
    Passionate about writing beautiful and clean code

Nice to have

    Experience with JavaScript, React.js, etc.
    Experience working with AWS cloud architecture (Docker, Kubernetes, CI/CD Pipelines)
    Experience working remotely
    Familiar/involved with open source projects

Personal

    Independent
    Fluent in English, written and spoken
    Problem solver
    Proactive attitude
