#+TITLE: Ansible

* Summary
:PROPERTIES:
:TOC:      :include all
:END:
:CONTENTS:
- [[#summary][Summary]]
- [[#progress][Progress]]
  - [[#books][Books]]
- [[#playbooks][Playbooks]]
  - [[#ansible-playbook][ansible-playbook]]
    - [[#options][options]]
      - [[#--connectionlocal][--connection=LOCAL]]
      - [[#--inventorypath][--inventory=PATH]]
      - [[#--extra-varsvars][--extra-vars=VARS]]
      - [[#--connectiontype][--connection=TYPE]]
      - [[#--forksnum][--forks=NUM]]
      - [[#--limitips][--limit=IPs]]
      - [[#--user][--user]]
      - [[#--check][--check]]
      - [[#--become-user][--become-user]]
      - [[#--become-method][--become-method]]
      - [[#--list-hosts][--list-hosts]]
      - [[#--force-handlers][--force-handlers]]
      - [[#--tags][--tags]]
      - [[#--skip-tags][--skip-tags]]
    - [[#run-local][run local]]
  - [[#usage][usage]]
  - [[#statements][statements]]
    - [[#when][when]]
    - [[#changed_when][changed_when]]
    - [[#failed_when][failed_when]]
    - [[#ignore_errors][ignore_errors]]
    - [[#delegate_to][delegate_to]]
    - [[#local_action][local_action]]
    - [[#tags][tags]]
    - [[#blocks][blocks]]
    - [[#handlers][handlers]]
    - [[#vars][vars]]
    - [[#var_files][var_files]]
    - [[#with_items][with_items]]
    - [[#name][name]]
    - [[#hosts][hosts]]
    - [[#become][become]]
    - [[#environment][environment]]
    - [[#import_tasks][import_tasks]]
    - [[#include_tasks][include_tasks]]
    - [[#import_playbooks][import_playbooks]]
  - [[#tips][tips]]
  - [[#modules][modules]]
    - [[#service][service]]
    - [[#script][script]]
    - [[#raw][raw]]
    - [[#template][template]]
    - [[#command][command]]
    - [[#stat][stat]]
    - [[#meta][meta]]
    - [[#composer][composer]]
    - [[#lineinfile][lineinfile]]
    - [[#file][file]]
    - [[#copy][copy]]
    - [[#get_url][get_url]]
    - [[#mysql_user][mysql_user]]
    - [[#mysql_db][mysql_db]]
    - [[#apache2_module][apache2_module]]
    - [[#apt][apt]]
    - [[#yum][yum]]
    - [[#dnf][dnf]]
  - [[#handler][handler]]
    - [[#notify][notify]]
  - [[#roles][roles]]
  - [[#tips][tips]]
    - [[#running-ansible-command-locally][running ansible command locally]]
  - [[#good-practices][good practices]]
  - [[#traits][traits]]
- [[#inventory][Inventory]]
  - [[#variables][variables]]
  - [[#example][example]]
- [[#commands][Commands]]
  - [[#ansible-galaxy][ansible-galaxy]]
    - [[#list][list]]
    - [[#collection-install][collection install]]
  - [[#ansible-inventory][ansible-inventory]]
    - [[#from-ini-to-yaml][from ini to yaml]]
  - [[#ansible][ansible]]
    - [[#host][<HOST>]]
    - [[#options][options]]
      - [[#-b-or---become][-b or --become]]
      - [[#-k-or---ask-become-pass][-K or --ask-become-pass]]
      - [[#-a-or---argument][-a or --argument]]
      - [[#-i][-i]]
      - [[#-m][-m]]
      - [[#-f][-f]]
      - [[#--limit][--limit]]
      - [[#-m-setup][-m setup]]
      - [[#-b-seconds][-B <seconds>]]
      - [[#-p-seconds][-P <seconds>]]
      - [[#--force-handlers][--force-handlers]]
- [[#variables][Variables]]
  - [[#acessing-variables][acessing variables]]
  - [[#ansible_envhome][ansible_env.HOME]]
  - [[#defaultruntime][default/runtime]]
    - [[#hostvars][hostvars]]
    - [[#groups][groups]]
    - [[#play_hosts][play_hosts]]
    - [[#inventory_hostname_short][inventory_hostname_short]]
    - [[#group_names][group_names]]
    - [[#inventory_hostname][inventory_hostname]]
  - [[#ansible_host_key_checking][ANSIBLE_HOST_KEY_CHECKING]]
  - [[#ansible_inventory][ANSIBLE_INVENTORY]]
  - [[#group_vars][group_vars]]
  - [[#group_varsall][group_vars/all]]
  - [[#host_vars][host_vars]]
  - [[#inventory-variables][inventory variables]]
  - [[#extra-vars-cli][extra-vars (cli)]]
  - [[#registered-variables][registered variables]]
  - [[#groups][groups]]
  - [[#group_names][group_names]]
  - [[#inventory_hostname][inventory_hostname]]
  - [[#inventory_hostname_short][inventory_hostname_short]]
  - [[#play_hosts][play_hosts]]
  - [[#facts][facts]]
  - [[#local-facts][local facts]]
  - [[#variable-precedence][variable precedence]]
  - [[#vars_prompt][vars_prompt]]
- [[#modules][Modules]]
  - [[#services][services]]
  - [[#wait_for][wait_for]]
  - [[#commands][commands]]
  - [[#shell][shell]]
  - [[#cron][cron]]
  - [[#git][git]]
  - [[#groups][groups]]
  - [[#user][user]]
  - [[#easy_install][easy_install]]
  - [[#mysql_][mysql_*]]
  - [[#package][package]]
  - [[#stat][stat]]
  - [[#docker][docker]]
    - [[#docker_image][docker_image]]
    - [[#docker_container][docker_container]]
  - [[#copy][copy]]
  - [[#rsync][rsync]]
  - [[#unarchive][unarchive]]
  - [[#synchronize][synchronize]]
  - [[#fetch][fetch]]
  - [[#file][file]]
  - [[#debug][debug]]
  - [[#meta][meta]]
  - [[#async_status][async_status]]
  - [[#yum][yum]]
  - [[#apt][apt]]
- [[#defition][Defition]]
- [[#traits][Traits]]
- [[#ssh][SSH]]
- [[#tower][Tower]]
- [[#vault][Vault]]
  - [[#ansible-vault][ansible-vault]]
    - [[#give-pass][give pass]]
    - [[#encrypt][encrypt]]
    - [[#edit][edit]]
    - [[#rekey][rekey]]
    - [[#create][create]]
    - [[#decrypt][decrypt]]
    - [[#pass-via-file][pass via file]]
:END:
* Progress
** Books
| Books              | Chapter         | @ |
|--------------------+-----------------+---|
| Ansible for DevOps | 7 - Inventories |   |

* Playbooks
** ansible-playbook
*** options
**** --connection=LOCAL
**** --inventory=PATH
calls a custom inventory file
**** --extra-vars=VARS
set additional variables as key=value or YAML/JSON
**** --connection=TYPE
connection type to use
**** --forks=NUM
specify number of parallel processes to use
**** --limit=IPs
further limit selected hosts to an additional pattern
**** --user
run operations with become

#+begin_src shell
ansible-playbook playbook.yml --user=johndoe
#+end_src
**** --check
don't make any changes; instead, try to predict some of the changes that may occur
**** --become-user
run operations as this user

#+begin_src shell
ansible-playbook playbook.yml --become --become-user=janedoe --ask-become-pass
#+end_src
**** --become-method
privilege escalation method to use
**** --list-hosts
**** --force-handlers
**** --tags
**** --skip-tags
*** run local
#+begin_src shell
ansible-playbook \
    --connection=local \
    --inventory 127.0.0.1, \
    --limit 127.0.0.1 ~/Documents/Ansible/local_playbook.yml
#+end_src
** usage
      - docker container
      - vagrant container
      - cloud instance
      - bare metal
** statements
*** when
#+begin_src yaml
- stat: path=/etc/hosts
  register: hosts_file
- copy: src=path/to/local/file dest=/path/to/remote/file
  when: hosts_file.stat.exists == false
#+end_src
*** changed_when
*** failed_when
*** ignore_errors
*** delegate_to

#+begin_src yaml
- name: Add server to Munin monitoring configuration.
  command: monitor-server webservers {{ inventory_hostname }}
  delegate_to: "{{ monitoring_master }}"
#+end_src
*** local_action
*** tags
Tags allow you to run (or exclude) subsets of a playbook’s tasks.

#+begin_src shell
ansible-playbook tags.yml --tags "tomcat,say"
#+end_src

#+begin_src yaml
---
# You can apply tags to an entire play.
- hosts: webservers
  tags: deploy

  roles:
    # Tags applied to a role will be applied to tasks in the role.
    - { role: tomcat, tags: ['tomcat', 'app'] }

  tasks:
    - name: Notify on complet
      local_action:
        module: osx_say
        msg: "{{inventory_hostname}} is finished!"
        voice: Zarvox
  tags:
    - notifications
    - say
  - import_tasks: foo.yml
    tags: foo
#+end_src
*** blocks
Blocks create logical groups of tasks. Blocks also offer ways to handle task
errors, similar to exception handling in many programming languages.

#+begin_src yaml
---
- hosts: web
  tasks:
    # Install and configure Apache on RHEL/CentOS hosts.
    - block:
        - yum: name=httpd state=present
        - template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf
        - service: name=httpd state=started enabled=yes
      when: ansible_os_family == 'RedHat'
      become: yes

# Install and configure Apache on Debian/Ubuntu hosts.
- block:
    - apt: name=apache2 state=present
    - template: src=httpd.conf.j2 dest=/etc/apache2/apache2.conf
    - service: name=apache2 state=started enabled=yes
  when: ansible_os_family == 'Debian'
  become: yes
#+end_src

#+begin_src yaml
tasks:
  - block:
      - name: Script to connect the app to a monitoring service.
        script: monitoring-connect.sh
    rescue:
      - name: This will only run in case of an error in the block.
        debug: msg="There was an error in the block."
    always:
      - name: This will always run, no matter what.
        debug: msg="This always executes."
#+end_src

*** handlers
*** vars
*** var_files
*** with_items
*** name
*** hosts
*** become
*** environment
set the environment for just one play
*** import_tasks
Imports a list of tasks to be added to the current playbook for subsequent execution.

#+begin_src yaml
tasks:
- import_tasks: imported-tasks.yml
- import_tasks: tasks/drush.yml tags=drush
#+end_src

#+begin_src yaml
tasks:
  - import_tasks: user.yml
    vars:
      username: johndoe
      ssh_private_keys:
        - { src: /path/to/johndoe/key1,dest: id_rsa }
        - { src: /path/to/johndoe/key2,dest: id_rsa_2 }
  - import_tasks: user.yml
    vars:
      username: janedoe
      ssh_private_keys:
        - { src: /path/to/janedoe/key1,dest: id_rsa }
        - { src: /path/to/janedoe/key2,dest: id_rsa_2 }
#+end_src
*** include_tasks
Includes a file with a list of tasks to be executed in the current playbook.

#+begin_src yaml
# Include extra tasks file, only if it's present at runtime.
- name: Check if extra_tasks.yml is present.
  stat: path=tasks/extra-tasks.yml
  register: extra_tasks_file
  connection: local

- include_tasks: tasks/extra-tasks.yml
  when: extra_tasks_file.stat.exists
#+end_src
*** import_playbooks
#+begin_src yaml
- hosts: all
  remote_user: root

tasks:
  [...]

- import_playbook: web.yml
- import_playbook: db.yml
#+end_src

#+begin_src yaml
---
- hosts: all
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  handlers:
    - import_tasks: handlers/handlers.yml

  tasks:
    - import_tasks: tasks/common.yml
    - import_tasks: tasks/apache.yml
#+end_src

** tips
- build your playbooks in a way that doesn’t rely (or care about) specific details of individual hosts.
** modules
*** service
*** script
*** raw
*** template
#+begin_src yaml
- name: Add Apache virtualhost for Drupal.
  template:
    src: "templates/drupal.test.conf.j2"
    dest: "/etc/apache2/sites-available/{{ domain }}.test.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
#+end_src
*** command
*** stat
*** meta
*** composer
*** lineinfile
*** file
*** copy
*** get_url
*** mysql_user
*** mysql_db
*** apache2_module
*** apt
*** yum
*** dnf
** handler
- • If the play fails on a particular host (or all hosts) before handlers are notified, the handlers will never be run.

*** notify
- will run once, and only once, at the end of a play

#+begin_src yaml
- name: Enable Apache rewrite module (required for Drupal).
    apache2_module: name=rewrite state=present
    notify: restart apache
#+end_src

#+begin_src yaml
- name: Rebuild application configuration.
  command: /opt/app/rebuild.sh
notify:
  - restart apache
  - restart memcached

#+end_src
** roles
Roles let you automatically load related vars, files, tasks, handlers, and other
Ansible artifacts based on a known file structure. After you group your content
in roles, you can easily reuse them and share them with other users.

- ./roles

#+begin_src yaml
--
- hosts: all
  roles:
    - role_name
#+end_src

** tips
*** running ansible command locally
       ansible-playbook --connection=local --inventory 127.0.0.1, playbook.yml
** good practices
      - naming plays
** traits
      - hosts: execute tasks
      - execute multiple modules in sequence
      - organized in tasks
      - arguments
      - modules name
* Inventory
- list of the hosts that you wish to run the automation commands against
- Ip addres or hostname
- webservers: groups multiple ip addresses or hosts names
- databases
- can dynamic inventories
- inventory location: /etc/ansible/hosts

** variables
- documentation recommends not storing variables within the inventory.

#+begin_src conf
# Host-specific variables (defined inline).
[washington]
app1.example.com proxy_state=present
app2.example.com proxy_state=absent
# Variables defined for the entire group.
[washington:vars]
cdn_host=washington.static.example.com
api_version=3.0.1
#+end_src
#+begin_src conf
[group]
host1 admin_user=jane
host2 admin_user=jack
host3

[group:vars]
admin_user=john
#+end_src

** example
#+begin_src conf
[example]
ubuntu ansible_host=18.1 ansible_connection=ssh ansible_user=ubuntu ansible_ssh_private_key_file=/home/meh/Documents/meh.pem
#+end_src
* Commands
|                           |                           |
|---------------------------+---------------------------|
| -m <MODULE> -a <OPT_ARGS> | use module with arguments |
| --ask-become-pass         | run command as sudo       |
| --ask-pass                | still require pass        |
| -a                        | module arguments          |
| -k                        | ask pass                  |
** ansible-galaxy
*** list
*** collection install

** ansible-inventory

*** from ini to yaml
#+begin_src shell
ansible-inventory -i hosts.ini -y --list > inventory.yaml
#+end_src

** ansible
Define and run a single task 'playbook' against a set of hosts

*** <HOST>

*** options
**** -b or --become
**** -K or --ask-become-pass
**** -a or --argument
**** -i
**** -m
**** -f
**** --limit
- reserve the --limit option for running commands on single servers

#+begin_src shell
ansible app -b -a "service ntpd restart" --limit "192.168.60.4"

# Limit hosts with a simple pattern (asterisk is a wildcard).
ansible app -b -a "service ntpd restart" --limit "*.4"

# Limit hosts with a regular expression (prefix with a tilde).
ansible app -b -a "service ntpd restart" --limit ~".*\.4"
#+end_src
**** -m setup
**** -B <seconds>
**** -P <seconds>
**** --force-handlers
* Variables
** acessing variables
#+begin_src yaml
- command: /opt/my-app/rebuild {{ my_environment }}  # /opt/my-app/rebuild dev
#+end_src

#+begin_src yaml
foo_list:
- one
- two
- three

foo[0]
foo|first

{{ ansible_eth0.ipv4.address }}
{{ ansible_eth0['ipv4']['address'] }}

#+end_src

** ansible_env.HOME
      get remote home

** default/runtime
*** hostvars
contains all the defined host variables (from inventory files and any discovered YAML files inside host_vars directories).
*** groups
A list of all group names in the inventory.
*** play_hosts
All hosts on which the current play will be run.
*** inventory_hostname_short
The first part of inventory_hostname , up to the first period.
*** group_names
A list of all the groups of which the current host is a part.
*** inventory_hostname
The hostname of the current host, according to the inventory (this can differ
from ansible_hostname , which is the hostname reported by the system).
** ANSIBLE_HOST_KEY_CHECKING
** ANSIBLE_INVENTORY
** group_vars
| default location   |                           |
|--------------------+---------------------------|
| root of project    | root/group_vars           |
| inventory's folder | root/inventory/group_vars |

# group_vars/washington
#+begin_src yaml
---
meh: bao
forevis: eija
#+end_src
** group_vars/all
apply to all groups

- it’s best to provide defaults in your playbooks and roles
** host_vars
| default location   |                          |
|--------------------+--------------------------|
| root of project    | root/host_vars           |
| inventory's folder | root/inventory/host_vars |

# ./host_vars/app1.example.com
#+begin_src yaml
---
foo: bar
baz: qux
#+end_src

** inventory variables

- documentation recommends not storing variables within the inventory
#+begin_src config
# Host-specific variables (defined inline).
[washington]
app1.example.com proxy_state=present
app2.example.com proxy_state=absent

# Variables defined for the entire group.
[washington:vars]
cdn_host=washington.static.example.com
api_version=3.0.1

[group]
host1 admin_user=jane
host2 admin_user=jack
host3

[group:vars]
admin_user=john
#+end_src
** extra-vars (cli)
#+begin_src shell
ansible-playbook example.yml --extra-vars "foo=bar"
ansible-playbook example.yml --extra-vars "@even_more_vars.json"
ansible-playbook example.yml --extra-vars "@even_more_vars.yml"
#+end_src
** registered variables
use return code of runned command, stderr, or stdout to determine whether to run a later task.
** groups
** group_names
** inventory_hostname
** inventory_hostname_short
** play_hosts
** facts
variables derived from system information

#+begin_src shell
ansible munin -m setup
#+end_src

#+begin_src yaml
- hosts: db
gather_facts: no
#+end_src
** local facts
defining host-specific facts

- either JSON or INIÁ
- facts.d/XX.ini

# ./facts.d/settings.fact
#+begin_src conf
[users]
admin=jane,john
normal=jim
#+end_src

#+begin_src shell
ansible hostname -m setup -a "filter=ansible_local"
#+end_src

relo ad the local facts using a task

#+begin_src yaml
- name: Reload local facts.
  setup: filter=ansible_local
#+end_src
** variable precedence
** vars_prompt
#+begin_src yaml
---
- hosts: all

vars_prompt:
  - name: share_user
    prompt: "What is your network username?"

  - name: share_pass
    prompt: "What is your network password?"
    private: yes
#+end_src

- private
- default
- encrypt
- confirm
- salt_size

* Modules
- grouped together
- one action may require multiple module
- applied in sequences

** services

#+begin_src shell
ansible multi -b -m service -a "name=ntpd state=started enabled=yes"
#+end_src
** wait_for
** commands
** shell
able to redirect and filter output from a command
#+begin_src shell
ansible multi -b -m shell -a "tail /var/log/messages | grep ansible-command | wc -l"
#+end_src

#+begin_src yaml
- name: Get the value of the environment variable we just added.
shell: 'source ~/.bash_profile && echo $ENV_VAR'
register: foo
#+end_src

** cron
#+begin_src shell
ansible multi -b -m cron -a "name='daily-cron-all-servers' hour=4 job='/path/to/daily-script.sh'"
ansible multi -b -m cron -a "name='daily-cron-all-servers' state=absent"
#+end_src
** git
#+begin_src shell
ansible app -b -m git -a "repo=git://example.com/path/to/repo.git dest=/opt/myapp update=yes version=1.2.4"
#+end_src
** groups

#+begin_src shell
ansible app -b -m group -a "name=admin state=present"
#+end_src

- name
- state
- gid=[gid]
- system=[yes|no]
** user
#+begin_src shell
ansible app -b -m user -a "name=johndoe group=admin createhome=yes"
#+end_src

- createhome=[yes|no]
- group=[group]
** easy_install
** mysql_*
** package
#+begin_src shell
ansible app -b -m package -a "name=git state=present"
#+end_src
** stat
#+begin_src shell
ansible multi -m stat -a "path=/etc/environment"
#+end_src
** docker
*** docker_image
*** docker_container

** copy
#+begin_src shell
ansible multi -m copy -a "src=/etc/hosts dest=/tmp/hosts"
#+end_src
** rsync
** unarchive
** synchronize
** fetch
Fetch files from remote nodes

#+begin_src shell
ansible multi -b -m fetch -a "src=/etc/hosts dest=/tmp"
#+end_src
** file
#+begin_src shell
ansible multi -m file -a "dest=/tmp/test mode=644 state=directory"
ansible multi -m file -a "src=/src/file dest=/dest/symlink state=link"
ansible multi -m file -a "dest=/tmp/test state=absent"
#+end_src
** debug
** meta
run handlers in the middle of a playbook
** async_status
#+begin_src shell
ansible multi -b -m async_status -a "jid=169825235950.3572"
#+end_src
** yum
#+begin_src shell
ansible multi -b -m yum -a "name=ntp state=present"
#+end_src
** apt
- name=string
- update_cache=[yes|no]
- state=[present|absent]
* Defition
Tool to automate IT tasks
* Traits
- requires python
- agentless
- support os, cloud
- reusable file configuration for different env
- yaml
- configuration
- mainly configuration
- deployment
- install/update software
- better in configuring
- procedural
* SSH
Pipelining method of OpenSSH transfer will send and execute commands for most
Ansible modules directly over the SSH connection.

- necessary to comment the 'Defaults requiretty' option in /etc/sudoers

ansible.cfg
#+begin_src conf
[ssh_connection]
pipelining=True
#+end_src
* Tower
- ui dashboard from redhat
- centrally automate tools
- across teams
- configure permissions
- manage inventory
* Vault
** ansible-vault
- works with one or multiple files

*** give pass
#+begin_src shell
ansible-playbook test.yml --ask-vault-pass
#+end_src

*** encrypt

#+begin_src shell
ansible-vault encrypt api_key.yml
#+end_src

*** edit
*** rekey
*** create
*** decrypt
*** pass via file

#+begin_src shell
ansible-playbook test.yml --vault-password-file ~/.ansible/vault_pass
#+end_src

use an executable script (e.g. ∼/.ansible/vault_pass.py with execute
permissions, 700), as long as the script outputs a single line of text, the vault password.

#+begin_src shell
∼/.ansible/vault_pass.py
#+end_src
